---
title: "Make_Figures"
author: "Molly Stroud"
format: html
editor: visual
---

## This document creates all figures shown in the paper

```{r}
# Load in libraries
require(pacman)
pacman::p_load(dplyr, ggplot2, patchwork, tidyverse, lubridate, viridis, wesanderson, patchwork)
```

## Figure 2

```{r}
# This figure shows the aggregated CRPS of all sites across all depths
scores_aggregated <- arrow::open_dataset("scores/parquet/") |>
  dplyr::collect() |>
  filter(datetime > "2021-01-01") |>
  filter(variable == "temperature") |>
  filter(horizon > 0) |>
  mutate(model_id = as.factor(model_id)) |>
  group_by(model_id, horizon) |>
  summarize(median_crps = median(crps, na.rm = T),
            mean_crps = mean(crps, na.rm = T))

levels(scores_aggregated$model_id) <- c("No DA", "In situ (all depths)", "In situ (RS frequency)", "In situ (surface)", "RS", "RS (in situ uncertainty)")
  
  
groups <- c("No DA", "In situ (all depths)", "In situ (surface)", "In situ (RS frequency)", "RS", "RS (in situ uncertainty)")

ggplot(data = scores_aggregated, 
       aes(x = horizon, y = median_crps, colour = model_id, linetype = model_id)) +
  geom_line(linewidth = 0.9) +
  #scale_colour_viridis_d(labels = c("No DA", "In situ (all depths)", "In situ (surface)", "In situ (RS frequency)", "RS", "RS (in situ uncertainty)")) +
  scale_linetype_manual(name = "",
                        values = setNames(c("solid", "solid", "dashed", "dotted", "solid", "dashed"), groups))  +
  scale_color_manual(name = "", 
                     values = setNames(c("#440154FF", "#2A788EFF","#2A788EFF","#2A788EFF", "#7AD151FF","#7AD151FF"), groups)) +

  labs(y = 'Median CRPS (°C)', x = 'Horizon (days ahead)', color = "") +
  theme_bw() +
  theme(legend.key.width = unit(2, "line"))

ggsave(paste0('paper_figs/', 'Figure2.png'), width = 6, height = 3, units = 'in', dpi = 400)

```

## Figure 3

```{r}
# This figure shows the aggregated CRPS across depths for each of the 10 sites
scores_sites <- arrow::open_dataset("scores/parquet/") |>
  dplyr::collect() |>
  filter(datetime > "2021-01-01") |>
  filter(variable == "temperature") |>
  filter(horizon > 0) |>
  mutate(model_id = as.factor(model_id)) |>
  group_by(model_id, horizon, site_id) |>
  summarize(crps = median(crps, na.rm = T),
            rmse = sqrt(mean((observation - median), na.rm = T)^2))

levels(scores_sites$model_id) <- c("No DA", "In situ (all depths)", "In situ (RS frequency)", "In situ (surface)", "RS", "RS (in situ uncertainty)")

groups <- c("No DA", "In situ (all depths)", "In situ (surface)", "In situ (RS frequency)", "RS", "RS (in situ uncertainty)")

sitenames <- as_labeller(c("BARC" = "Lake Barco",
               "bvre" = "Beaverdam\nReservoir",
               "ccre" = "Carvins Cove\nReservoir",
               "CRAM" = "Crampton Lake",
               "fcre" = "Falling Creek\nReservoir",
               "LIRO" = "Little Rock\nLake",
               "PRLA" = "Prairie\nLake",
               "PRPO" = "Prairie\nPothole",
               "SUGG" = "Lake Suggs",
               "sunp" = "Lake Sunapee"))

# without prairie lakes
without_pr <- ggplot(data = scores_sites[scores_sites$site_id != "PRPO" & scores_sites$site_id != "PRLA",], 
       aes(x = horizon, y = crps, colour = model_id, linetype = model_id)) +
  geom_line(linewidth = 0.5) +
  facet_wrap(~site_id, nrow = 2, labeller = sitenames) +
  #scale_colour_viridis_d()+#begin = 0.2, end = 0.8, 
                         #labels = c("No DA", "With in situ", "With RS")) +
  scale_linetype_manual(name = "",
                        values = setNames(c("solid", "solid", "dashed", "dotted", "solid", "dashed"), groups))  +
  scale_color_manual(name = "", 
                     values = setNames(c("#440154FF", "#2A788EFF","#2A788EFF","#2A788EFF", "#7AD151FF","#7AD151FF"), groups)) +
  labs(y = 'Median CRPS (°C)', x = 'Horizon (days ahead)', color = "") +
  theme_bw() +
  theme(legend.position = 'bottom', legend.margin = margin(t = -10),
        strip.text = element_text(size=8), legend.key.width = unit(2, "line"))
without_pr

# with prairie lakes
with_pr <- ggplot(data = scores_sites[scores_sites$site_id == "PRPO" | scores_sites$site_id == "PRLA",], 
       aes(x = horizon, y = crps, colour = model_id, linetype = model_id)) +
  geom_line(linewidth = 0.5) +
  facet_wrap(~site_id, nrow = 2, labeller = sitenames) +
  #scale_colour_viridis_d()+#begin = 0.2, end = 0.8, 
                         #labels = c("No DA", "With in situ", "With RS")) +
  scale_linetype_manual(name = "",
                        values = setNames(c("solid", "solid", "dashed", "dotted", "solid", "dashed"), groups))  +
  scale_color_manual(name = "", 
                     values = setNames(c("#440154FF", "#2A788EFF","#2A788EFF","#2A788EFF", "#7AD151FF","#7AD151FF"), groups)) +
  labs(y = 'Median CRPS (°C)', x = 'Horizon (days ahead)', color = "") +
  theme_bw() +
  theme(legend.position = 'bottom', legend.margin = margin(t = -10),
        strip.text = element_text(size=8))
with_pr

without_pr + with_pr + 
  plot_layout(widths = c(4,1), guides = "collect", axis_titles = "collect") &
  theme(legend.position = 'bottom', strip.text = element_text(size = 9), legend.key.width = unit(2, "line"))
  #theme(legend.position = "bottom", strip.text = element_text(size = 6))


ggsave(paste0('paper_figs/', 'Figure3.png'), width = 6, height = 4, units = 'in', dpi = 400)

```

## Figure 4

```{r}
# This figure shows the remote sensing temperature estimates plotted against the in situ temperature estimates
folders <- list.files("/Users/mollystroud/Desktop/postdoc/flare-rs-thermal/targets", full.names = T)
library(stringr)
alldata <- data.frame()
for(folder in folders){
  name <- str_sub(folder, start = -4)
  insitu <- read_csv(paste0(folder, '/', name, '-targets-insitu.csv')) |>
    filter(!is.na(observation)) |>
    filter(as.Date(datetime) >= "2021-01-02") |>
    slice_min(depth, n = 1) |>
    rename(insitu = observation) 
  rs <- read_csv(paste0(folder, '/', name, '-targets-rs.csv'))
  data <- left_join(rs, insitu, by = c('datetime', 'site_id'))
  alldata <- rbind(data, alldata)
}
alldata <- na.omit(alldata) |>
  group_by(site_id) |>
  mutate(sd_resid = sd(observation - insitu))

# Now, show the (RS estimates vs. in situ estimates) vs. the overall accuracy of each site
overall_accuracy <- arrow::open_dataset("scores/parquet/") |>
  dplyr::collect() |>
  filter(datetime > "2021-01-01") |>
  filter(variable == "temperature") |>
  filter(horizon > 0) |>
  filter(model_id == "analysis_run_with_rs") |>
  group_by(site_id) |>
  summarize(median_crps = median(crps, na.rm = T),
            mean_crps = mean(crps, na.rm = T))

results <- alldata |>
  group_by(site_id) |>
  summarize(bias = median(observation - insitu, na.rm = T))

results_all <- left_join(results, overall_accuracy, by = c("site_id"))

ggplot(results_all, aes(x = median_crps, y = abs(bias), color = site_id)) +
  geom_point() +
  theme_bw() +
  geom_smooth(se = F, method = 'lm', aes(group = 1), 
              color = 'gray50', linetype = 'dashed') +
  scale_color_manual(values = wes_palette(10, name = "Zissou1", type = 'continuous'),
                     labels = c("BARC" = "Lake Barco",
                                "bvre" = "Beaverdam Reservoir",
                                "ccre" = "Carvins Cove Reservoir",
                                "CRAM" = "Crampton Lake",
                                "fcre" = "Falling Creek Reservoir",
                                "LIRO" = "Little Rock Lake",
                                "PRLA" = "Prairie Lake",
                                "PRPO" = "Prairie Pothole",
                                "SUGG" = "Lake Suggs",
                                "sunp" = "Lake Sunapee")) +
  labs(x = "Median CRPS (°C)", y = "Remote sensing observation \n median absolute bias (°C)",
       color = "")

ggsave(paste0('paper_figs/', 'Figure4.png'), width = 5, height = 3, units = 'in', dpi = 400)

```

## Figure 5

```{r}
# This figure shows the CRPS for each site at each depth for forecasts with RS data assimilation, as well as the difference in CRPS for each site between RS data assimilation and no data assimilation
scores_depth <- arrow::open_dataset("scores/parquet/") |>
    dplyr::collect() |>
    filter(datetime > "2021-01-01") |>
    filter(variable == "temperature") |>
    filter(horizon == 1) |>
    group_by(model_id, horizon, site_id, depth) |>
    summarize(median_crps = median(crps, na.rm = T),
              mean_crps = mean(crps, na.rm = T))
  
scores_depth <- scores_depth |>
  arrange(site_id, depth) |>
  na.omit()

rs_depth <- ggplot(scores_depth[scores_depth$model_id == "analysis_run_with_rs",], 
       aes(x = median_crps, y = depth, color = site_id, group = site_id)) +
  geom_line(orientation = "y", linewidth = 0.9) +
  geom_point(size = 1) +
  theme_bw() +
  scale_color_manual(values = wes_palette(10, name = "Zissou1", type = 'continuous'),
                     labels = c("BARC" = "Lake Barco",
                                "bvre" = "Beaverdam\nReservoir",
                                "ccre" = "Carvins Cove\nReservoir",
                                "CRAM" = "Crampton Lake",
                                "fcre" = "Falling Creek\nReservoir",
                                "LIRO" = "Little Rock Lake",
                                "PRLA" = "Prairie Lake",
                                "PRPO" = "Prairie Pothole",
                                "SUGG" = "Lake Suggs",
                                "sunp" = "Lake Sunapee")) +
  scale_y_continuous(trans = c("reverse")) +
  labs(x = "Median CRPS (°C)", y = "Depth (m)", color = "", tag = "(a)") +
  theme(plot.tag.position = c(0.02, 1))


diff_df <- scores_depth |>
  group_by(horizon, depth, site_id) |>
  summarise(median_crps_diff = median_crps[model_id == "analysis_run_with_rs"] - median_crps[model_id == "analysis_run_no_da"],
            mean_crps_diff   = mean_crps[model_id == "analysis_run_with_rs"] - mean_crps[model_id == "analysis_run_no_da"],
            .groups = "drop")

diff_depth <- ggplot(diff_df, 
       aes(x = median_crps_diff, y = depth, color = site_id, group = site_id)) +
    geom_vline(xintercept = 0, linetype = 'dashed', color = 'darkgray') +
  geom_line(orientation = "y", linewidth = 0.9) +
  geom_point(size = 1) +
  theme_bw() +
  scale_color_manual(values = wes_palette(10, name = "Zissou1", type = 'continuous'),
                     labels = c("BARC" = "Lake Barco",
                                "bvre" = "Beaverdam\nReservoir",
                                "ccre" = "Carvins Cove\nReservoir",
                                "CRAM" = "Crampton Lake",
                                "fcre" = "Falling Creek\nReservoir",
                                "LIRO" = "Little Rock Lake",
                                "PRLA" = "Prairie Lake",
                                "PRPO" = "Prairie Pothole",
                                "SUGG" = "Lake Suggs",
                                "sunp" = "Lake Sunapee")) +
  scale_y_continuous(trans = c("reverse")) +
  labs(x = 'Δ CRPS (°C; with RS - no DA)', y = "Depth (m)", color = "", tag = "(b)") +
  theme(plot.tag.position = c(0.02, 1)) +
  geom_vline(xintercept = 0, color = 'gray40', linetype = 'dashed') +
  annotate('text', x = -0.7, y = 11, label = 'RS performs\nbetter', 
           color = 'gray40', size = 3) +
  annotate('text', x = 0.75, y = 11, label = 'no DA\nperforms\nbetter', 
           color = 'gray40', size = 3)

rs_depth + diff_depth + plot_layout(guides = "collect", axis_titles = "collect")

ggsave(paste0('paper_figs/', 'Figure5.png'), width = 6.5, height = 4.5, units = 'in')

```

## Figure 6

```{r}
# This figure shows the CRPS of each site during each season, aggregated across depth
scores_seasonal <- arrow::open_dataset("scores/parquet/") |>
  dplyr::collect() |>
  filter(datetime > "2021-01-01") |>
  filter(variable == "temperature") |>
  #filter((month(datetime) >= 5 ) & (month(datetime) <= 9)) |> # SUMMER
  #filter((month(datetime) >= 10 ) | (month(datetime) <= 4)) |> # WINTER
  mutate(month = month(datetime), 
         season = case_when(
           month %in% c(12, 1, 2)  ~ "Winter",
           month %in% c(3, 4, 5)   ~ "Spring",
           month %in% c(6, 7, 8)   ~ "Summer",
           month %in% c(9, 10, 11) ~ "Fall")) |>
  filter(horizon > 0) |>
  group_by(site_id, model_id, horizon, season) |>
  summarize(median_crps = median(crps, na.rm = T))

ggplot(data = scores_seasonal[scores_seasonal$model_id == "analysis_run_with_rs",], 
       aes(x = horizon, y = median_crps, color = site_id)) +
  geom_line(linewidth = 1) +
  facet_wrap(~season) +
  scale_color_manual(values = wes_palette(10, name = "Zissou1", type = 'continuous')) +
  labs(y = 'CRPS (degree C)', x = 'Horizon (days ahead)', color = "") +
  theme_bw() +
  theme(legend.position = 'bottom')

#ggsave(paste0('paper_figs/', 'Figure6.png'), width = 6, height = 5, units = 'in')


delta_seasons <- scores_seasonal |>
  filter(model_id %in% c("analysis_run_no_da","analysis_run_with_rs")) |>
  pivot_wider(
    id_cols   = c(site_id, horizon, season),    # the keys that define a unique case
    names_from = model_id,                      # create a column for each model_id
    values_from = median_crps,
    names_glue = "median_{model_id}"            # nice column names
  ) |> mutate(
  diff_median_crps = median_analysis_run_with_rs -
    median_analysis_run_no_da) |>
  select(site_id, horizon, season,
         median_analysis_run_no_da,
         median_analysis_run_with_rs,
         diff_median_crps)

delta_seasons$season <- factor(delta_seasons$season, levels = c("Winter", "Spring", "Summer", "Fall"))

anno_df <- data.frame(
  season = factor("Winter", levels = c("Winter", "Spring", "Summer", "Fall")),
  x = 10,
  y = c(2.5, -0.7),
  label = c("no DA performs better", "RS performs better")
)
# This figure shows the difference in CRPS between RS and no RS for each season
ggplot(data = delta_seasons, aes(x = horizon, y = diff_median_crps, color = site_id)) +
  geom_line(linewidth = 1) +
  facet_wrap(~season) +
  scale_color_manual(values = wes_palette(10, name = "Zissou1", type = 'continuous'),
                     labels = c("BARC" = "Lake Barco",
                                "bvre" = "Beaverdam\nReservoir",
                                "ccre" = "Carvins Cove\nReservoir",
                                "CRAM" = "Crampton Lake",
                                "fcre" = "Falling Creek\nReservoir",
                                "LIRO" = "Little Rock Lake",
                                "PRLA" = "Prairie Lake",
                                "PRPO" = "Prairie Pothole",
                                "SUGG" = "Lake Suggs",
                                "sunp" = "Lake Sunapee")) +
  labs(y = 'Δ CRPS (RS - no DA) (°C)', x = 'Horizon (days ahead)', color = "") +
  theme_bw() +
  theme(legend.position = 'bottom', 
        legend.spacing.x = unit(0.1, 'cm'),
        legend.key.width = unit(0.5, 'cm')) +
  geom_hline(yintercept = 0, color = 'gray40', linetype = 'dashed') + 
  geom_text(data = anno_df, aes(x = x, y = y, label = label),
            color = 'gray40', inherit.aes = FALSE)


ggsave(paste0('paper_figs/', 'Figure6.png'), width = 6, height = 5, units = 'in')

# Now, just for surface estimates
# scores_seasonal_3m <- arrow::open_dataset("scores/parquet/") |>
#   dplyr::collect() |>
#   filter(datetime > "2021-01-01") |>
#   filter(variable == "temperature") |>
#   filter(!is.na(observation)) |>
#   group_by(site_id) |>
#   filter(depth == min(depth, na.rm = TRUE)) |>
#   ungroup() |>
#   mutate(month = month(datetime), 
#          season = case_when(
#            month %in% c(12, 1, 2)  ~ "Winter",
#            month %in% c(3, 4, 5)   ~ "Spring",
#            month %in% c(6, 7, 8)   ~ "Summer",
#            month %in% c(9, 10, 11) ~ "Fall")) |>
#   filter(horizon > 0) |>
#   group_by(site_id, model_id, horizon, season) |>
#   summarize(median_crps = median(crps, na.rm = T))
# 
# delta_seasons_3m <- scores_seasonal_3m |>
#   filter(model_id %in% c("analysis_run_no_da","analysis_run_with_rs")) |>
#   pivot_wider(
#     id_cols   = c(site_id, horizon, season),    # the keys that define a unique case
#     names_from = model_id,                      # create a column for each model_id
#     values_from = median_crps,
#     names_glue = "median_{model_id}"            # nice column names
#   ) |> mutate(
#     diff_median_crps = median_analysis_run_with_rs -
#       median_analysis_run_no_da) |>
#   select(site_id, horizon, season,
#          median_analysis_run_no_da,
#          median_analysis_run_with_rs,
#          diff_median_crps)
# 
# ggplot(data = delta_seasons_3m, aes(x = horizon, y = diff_median_crps, color = site_id)) +
#   geom_line(linewidth = 1) +
#   facet_wrap(~season) +
#   scale_color_manual(values = wes_palette(10, name = "Zissou1", type = 'continuous')) +
#   labs(y = 'Δ CRPS (RS - no DA) (°C)', x = 'Horizon (days ahead)', color = "") +
#   theme_bw() +
#   theme(legend.position = 'bottom') +
#   geom_hline(yintercept = 0, color = 'gray40', linetype = 'dashed') +
#   annotate('text', x = 10, y = 2.5, label = 'no DA performs better', color = 'gray40') +
#   annotate('text', x = 10, y = -0.7, label = 'RS performs better', color = 'gray40')
```

## Figure 7

```{r}
# This figure shows the reliability of RS forecasts aggregated across depths and at shallowest depths
reliability_scores <- arrow::open_dataset("scores/parquet/") |>
  dplyr::collect() |>
  filter(datetime > "2021-01-01") |>
  filter(variable == "temperature") |>
  filter(horizon > 0) |>
  filter(!is.na(observation)) |>
      mutate(is_in = between(observation, quantile10, quantile90)) |> 
      group_by(horizon, is_in, model_id, site_id) |> 
      summarise(n = n()) |> 
      pivot_wider(names_from = is_in, names_prefix = 'within_', values_from = n, values_fill = 0) |> 
      mutate(perc = within_TRUE/(within_FALSE + within_TRUE)*100)

  
rs_reliability <- ggplot(reliability_scores[reliability_scores$model_id == "analysis_run_with_rs",], 
       aes(x=horizon, y=perc, colour = site_id)) +
    geom_hline(yintercept = 90, colour = 'darkgray', linetype = 'dashed') +
    geom_line(alpha = 0.8, linewidth = 1) +
    labs(y = 'Percentage of observations within\n90% confidence intervals', 
         x ='Horizon (days)',
         color = "",
         tag = "(a)") +
    annotate('text', x = 10, y = 100, label = 'underconfident', 
             size = 4, hjust = 1, color = 'gray30') +
    annotate('text', x = 10, y = 20, label = 'overconfident',
             size = 4, hjust = 1, color = 'gray30') +
    theme_bw() +
    ylim(0, 100) +
  annotate('text', x = 14, y = 0, label = 'All depths', size = 4.5, hjust = 1) +
  scale_color_manual(values = wes_palette(10, name = "Zissou1", type = 'continuous'),
                     labels = c("BARC" = "Lake Barco",
                                "bvre" = "Beaverdam\nReservoir",
                                "ccre" = "Carvins Cove\nReservoir",
                                "CRAM" = "Crampton Lake",
                                "fcre" = "Falling Creek\nReservoir",
                                "LIRO" = "Little Rock Lake",
                                "PRLA" = "Prairie Lake",
                                "PRPO" = "Prairie Pothole",
                                "SUGG" = "Lake Suggs",
                                "sunp" = "Lake Sunapee")) +
  theme(plot.tag.position = c(0.02, 1))
#ggsave(paste0('paper_figs/', 'Figure6a.png'), width = 6, height = 5, units = 'in')

reliability_scores_surface <- arrow::open_dataset("scores/parquet/") |>
  dplyr::collect() |>
  filter(datetime > "2021-01-01") |>
  filter(variable == "temperature") |>
  filter(horizon > 0) |>
  filter(!is.na(observation)) |>
  group_by(site_id) |>
  filter(depth == min(depth, na.rm = TRUE)) |>
  ungroup() |>
  mutate(is_in = between(observation, quantile10, quantile90)) |> 
  group_by(horizon, is_in, model_id, site_id) |> 
  summarise(n = n()) |> 
  pivot_wider(names_from = is_in, names_prefix = 'within_', values_from = n, values_fill = 0) |>
  mutate(perc = within_TRUE/(within_FALSE + within_TRUE)*100)
  
rs_reliability_surface <- ggplot(reliability_scores_surface[reliability_scores_surface$model_id == "analysis_run_with_rs",], 
       aes(x=horizon, y=perc, colour = site_id)) +
    geom_hline(yintercept = 90, colour = 'darkgray', linetype = 'dashed') +
    geom_line(alpha = 0.8, linewidth = 1) +
    labs(y = 'Percentage of observations within\n90% confidence intervals', 
         x='Horizon (days)',
         color = "",
         tag = "(b)") +
    annotate('text', x = 10, y = 100, label = 'underconfident', 
             size = 4, hjust = 1, color = 'gray30') +
    annotate('text', x = 10, y = 20, label = 'overconfident',
             size = 4, hjust = 1, color = 'gray30') +
    annotate('text', x = 14, y = 0, label = 'Shallowest depths', size = 4.5, hjust = 1) +
    theme_bw() +
    ylim(0, 100) +
  scale_color_manual(values = wes_palette(10, name = "Zissou1", type = 'continuous'),
                     labels = c("BARC" = "Lake Barco",
                                "bvre" = "Beaverdam\nReservoir",
                                "ccre" = "Carvins Cove\nReservoir",
                                "CRAM" = "Crampton Lake",
                                "fcre" = "Falling Creek\nReservoir",
                                "LIRO" = "Little Rock Lake",
                                "PRLA" = "Prairie Lake",
                                "PRPO" = "Prairie Pothole",
                                "SUGG" = "Lake Suggs",
                                "sunp" = "Lake Sunapee")) +
  theme(plot.tag.position = c(0.02, 1))

rs_reliability + rs_reliability_surface + plot_layout(guides = "collect", axis_titles = "collect")

ggsave(paste0('paper_figs/', 'Figure7.png'), width = 6.5, height = 5, units = 'in')
 
```

## Figure 8

```{r}
# This figure shows the Spearman's correlation 
lake_info <- read_csv("LakeStats.csv")

accuracy_1day <- arrow::open_dataset("scores/parquet/") |>
  dplyr::collect() |>
  filter(datetime > "2021-01-01") |>
  filter(variable == "temperature") |>
  filter(horizon == 1) |>
  filter(model_id == "analysis_run_with_rs") |>
  group_by(site_id, horizon) |>
  summarize(crps = median(crps, na.rm = T)) |>
  ungroup() |>
  mutate(horizon = as.character(horizon)) |>
  select(horizon, site_id, crps) #|>
  #filter(site_id != "PRLA" & site_id != "PRPO")

minmax14day <- arrow::open_dataset("scores/parquet/") |>
  dplyr::collect() |>
  filter(datetime > "2021-01-01") |>
  filter(variable == "temperature") |>
  filter(model_id == "analysis_run_with_rs") |>
  group_by(site_id) |>
  summarize(crps = max(crps, na.rm = T) - min(crps, na.rm = T), .groups = 'drop') |>
  mutate(horizon = "max_min") |>
  select(horizon, site_id, crps) #|>
  #filter(site_id != "PRLA" & site_id != "PRPO")


# accuracy_14day <- arrow::open_dataset("scores/parquet/") |>
#   dplyr::collect() |>
#   filter(datetime > "2021-01-01") |>
#   filter(variable == "temperature") |>
#   filter(horizon == 14) |>
#   filter(model_id == "analysis_run_with_rs") |>
#   group_by(site_id) |>
#   summarize(crps_14 = median(crps, na.rm = T),
#             crps_maxmin = max(crps) - min(crps), .groups = 'drop')

# stats_spearman <- left_join(stats_orig, accuracy_1day, by = c("siteID" = "site_id"))
# stats_spearman <- left_join(stats_spearman, minmax14day, by = c("siteID" = "site_id"))
# #stats_spearman$crps_14_degrad <- stats_spearman$crps_14 - stats_spearman$crps_1
# 
# stats_spearman_long <- stats_spearman |>
#   pivot_longer(cols = -c(crps_1, crps_14, crps_14_degrad, lake_name, siteID, state, `Mixing Regime`, `Catchment cover`),
#                names_to = "variable",
#                values_to = "value")

day1_max_min <- bind_rows(accuracy_1day, minmax14day) %>% 
  left_join(lake_info, by = c("site_id" = "siteID"))

# spearman_corr_1 <- stats_spearman_long %>%
#   group_by(variable) %>%
#   summarise(
#     r = cor(value, -crps_1, method = "spearman"),
#     .groups = "drop"
#   )
# 
# spearman_corr_14 <- stats_spearman_long %>%
#   group_by(variable) %>%
#   summarise(
#     r = cor(value, crps_14_degrad, method = "spearman"),
#     .groups = "drop"
#   )

spear_corr_table <- day1_max_min |>
  select(crps, horizon, max_depth_m, fetch_m, volume_m3, surface_area_km2, mean_secchi_depth_m,
         mean_annual_temperature_degreeC, mean_annual_precipitation_mm, air_temp_10day_sd_degreeC, latitude, n_rs_images, rs_median_abs_bias, avg_wind, n_strat_days) |>
  pivot_longer(cols = -c("crps","horizon"), names_to = "variable", values_to = "value") |> 
  filter(horizon %in% c("1", "max_min")) |>
  group_by(horizon, variable) |>
  summarize(rho = cor(crps, value, method = "spearman"), 
            .groups = "drop") |>
  mutate(Metric = ifelse(horizon == "1",  "accuracy", "accuracy\ndegradation"),
         rho = ifelse(Metric == "accuracy", -rho, rho)) |>
  arrange(desc(abs(rho)))

variables <- tibble(variable = c("max_depth_m", "fetch_m", "volume_m3", "surface_area_km2", "mean_secchi_depth_m", "mean_annual_temperature_degreeC", "mean_annual_precipitation_mm", "air_temp_10day_sd_degreeC", "mean_hydraulic_residence_time_yrs", "catchment_size_km2", "latitude", "n_rs_images", "rs_median_abs_bias", "avg_wind", "n_strat_days"),
                    full_name = c("Maximum\ndepth", "Fetch", "Volume", "Surface\narea","Water clarity\n(Secchi depth)","Mean annual air\ntemperature", "Mean annual\nprecipitation","10-day variance in\n air temperature","Mean hydrologic\nresidence time","Catchment\nsize", "Latitude", "# RS images", "RS median\nabsolute bias", "Average\nwind speed", "# stratified days"))
spear_corr_table <- left_join(spear_corr_table, variables, by = "variable")

ggplot(spear_corr_table, aes(x = rho, y = full_name, color = Metric)) +
  geom_point(size = 2) +
  theme_bw() +
  xlim(-1, 1) +
  geom_vline(xintercept = -0.5, linetype = 'dashed') +
  geom_vline(xintercept = 0.5, linetype = 'dashed') +
  labs(x = "Spearman's correlation coefficient", y = element_blank(), color = element_blank()) +#,
       #title = "Excluding PRLA + PRPO") +
  scale_color_manual(values = c("accuracy
degradation" = '#277da1', "accuracy" = '#f94144'))

ggsave(paste0('paper_figs/', 'Figure8.png'), width = 7, height = 5, units = 'in')



# now look at values of each variable
lake_info <- left_join(lake_info, accuracy_1day, by = c("siteID" = "site_id"))

secchiplot <- ggplot(lake_info, aes(x = reorder(siteID, -mean_secchi_depth_m), y = mean_secchi_depth_m, fill = crps)) + 
  geom_bar(stat = 'identity') +
  theme_bw() +
  scale_fill_gradient(high = "#c1121f", low = "#2c7da0") +
  labs(x = element_blank(), y = "Mean Secchi (m)", fill = "CRPS (°C)") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
secchiplot

precipplot <- ggplot(lake_info, aes(x = reorder(siteID, -mean_annual_precipitation_mm), 
                                    y = mean_annual_precipitation_mm, fill = crps)) + 
  geom_bar(stat = 'identity') +
  theme_bw() +
  scale_fill_gradient(high = "#c1121f", low = "#2c7da0") +
  labs(x = element_blank(), y = "Mean annual precip (mm)", fill = "CRPS (°C)") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
precipplot

latplot <- ggplot(lake_info, aes(x = reorder(siteID, -latitude), 
                                    y = latitude, fill = crps)) + 
  geom_bar(stat = 'identity') +
  theme_bw() +
  scale_fill_gradient(high = "#c1121f", low = "#2c7da0") +
  labs(x = element_blank(), y = "Latitude", fill = "CRPS (°C)") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
latplot

windplot <- ggplot(lake_info, aes(x = reorder(siteID, -avg_wind), 
                                    y = avg_wind, fill = crps)) + 
  geom_bar(stat = 'identity') +
  theme_bw() +
  scale_fill_gradient(high = "#c1121f", low = "#2c7da0") +
  labs(x = element_blank(), y = "Wind speed", fill = "CRPS (°C)") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
windplot

tempvarplot <- ggplot(lake_info, aes(x = reorder(siteID, -air_temp_10day_sd_degreeC), 
                                    y = air_temp_10day_sd_degreeC, fill = crps)) + 
  geom_bar(stat = 'identity') +
  theme_bw() +
  scale_fill_gradient(high = "#c1121f", low = "#2c7da0") +
  labs(x = element_blank(), y = "Air temp 10 day sd", fill = "CRPS (°C)") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
tempvarplot



secchiplot + precipplot + latplot + windplot + tempvarplot + 
  plot_layout(nrow = 2, guides = 'collect')
ggsave(paste0('paper_figs/', 'FigureS2.png'), width = 10, height = 5, units = 'in')


```

## Supplementary figures

```{r}
# This figure shows the remote sensing temperature estimates plotted against the in situ temperature estimates

folders <- list.files("/Users/mollystroud/Desktop/postdoc/flare-rs-thermal/targets", full.names = T)
library(stringr)
alldata <- data.frame()
for(folder in folders){
  name <- str_sub(folder, start = -4)
  insitu <- read_csv(paste0(folder, '/', name, '-targets-insitu.csv')) |>
    filter(!is.na(observation)) |>
    filter(as.Date(datetime) >= "2021-01-02") |>
    slice_min(depth, n = 1) |>
    rename(insitu = observation) 
  rs <- read_csv(paste0(folder, '/', name, '-targets-rs.csv'))
  data <- left_join(rs, insitu, by = c('datetime', 'site_id'))
  alldata <- rbind(data, alldata)
}
alldata <- na.omit(alldata) |>
  group_by(site_id) |>
  mutate(sd_resid = sd(observation - insitu))

ggplot(alldata[alldata$datetime > "2020-10-01" & alldata$datetime < "2023-01-01",],
       aes(x = insitu, y = observation)) +
  geom_point(aes(color = as.Date(datetime)), alpha = 0.8, size = 2) +
  geom_abline(intercept = 0, slope = 1) +
  geom_smooth(se = F, color = 'maroon', method = 'lm') +
  facet_wrap(~site_id, nrow = 2, labeller = sitenames) +
  theme_bw() +
  scale_color_viridis_c(trans = 'date',
                        breaks = c(as.Date("2021-05-01"), as.Date("2022-10-01"))) +
  labs(x = 'In situ temperature (°C) ', y = 'Remote sensing temperature (°C)',
       color = element_blank()) +
  theme(legend.position = 'bottom') #+
  # geom_label(data = resids, aes(x = Inf, y = Inf,
  #                               label = paste("Stdev of resids = ", sd_resid)),
  #            hjust = 1, vjust = 1)
ggsave(paste0('paper_figs/', 'FigureS1.png'), width = 7, height = 5, units = 'in')


```

Figure X

```{r}
rs <- read_csv('/Users/mollystroud/Desktop/postdoc/flare-rs-thermal/targets/LIRO/LIRO-targets-rs.csv') |>
  filter(datetime > "2021-01-01" & datetime < "2023-01-01")


# OPEN DATA OF MEAN/OBSERVATION
scores <- arrow::open_dataset("scores/parquet/") |>
  dplyr::collect() |>
  filter(datetime > "2021-01-01") |>
  filter(variable == "temperature") |>
  filter(site_id == "LIRO") |>
  filter(model_id != "analysis_run_with_rs_05_obssd") |>
  filter(model_id != "analysis_run_no_da") |>
  group_by(datetime, site_id, model_id, depth) |>
  summarise_at(vars(median, observation, quantile97.5, quantile02.5), median, na.rm = TRUE) |>
  filter(depth == 0)
# PLOT
ggplot(data = scores, 
       aes(x = datetime, y = median, color = model_id)) +
  geom_line() +
  geom_ribbon(aes(ymax= quantile97.5,
                  ymin = quantile02.5,
                  fill = model_id), alpha = 0.5) +
  scale_colour_viridis_d(begin = 0.2, end = 0.8, 
                         labels = c("No DA", "With in situ", "With RS")) +
  scale_fill_viridis_d(begin = 0.2, end = 0.8, 
                         labels = c("No DA", "With in situ", "With RS")) +
  geom_point(data = scores, aes(x = datetime, y = observation, 
                                color = 'In Situ'), 
             alpha = 0.5, size = 0.7) +
  geom_point(data = rs, aes(x = datetime, y = observation, 
                            color = 'RS')) +
  scale_color_manual(values = c("In Situ" = 'black', 'RS' = 'maroon')) +
  #facet_wrap(~depth) +
  theme_classic() +
  labs(y = "Temp", x = "", color = "", fill = "")

ggsave(paste0('paper_figs/', 'FigureSX.png'), width = 5, height = 3, units = 'in', dpi = 400)

```

Compare RS obssd 1 and 0.5

```{r}
scores_sites <- arrow::open_dataset("scores/parquet/") |>
  dplyr::collect() |>
  filter(datetime > "2021-01-01") |>
  filter(variable == "temperature") |>
  filter(horizon > 0) |>
  filter(model_id == (c("analysis_run_with_rs", "analysis_run_with_rs_05_obssd"))) |>
  group_by(model_id, horizon, site_id) |>
  summarize(median_crps = median(crps, na.rm = T),
            mean_crps = mean(crps, na.rm = T))

sitenames <- as_labeller(c("BARC" = "Lake Barco",
               "bvre" = "Beaverdam Reservoir",
               "ccre" = "Carvins Cove Reservoir",
               "CRAM" = "Lake Crampton",
               "fcre" = "Falling Creek Reservoir",
               "LIRO" = "Little Rock Reservoir",
               "PRLA" = "Prairie Lake",
               "PRPO" = "Prairie Pothole",
               "SUGG" = "Lake Suggs",
               "sunp" = "Lake Sunapee"))

ggplot(data = scores_sites, aes(x = horizon, y = median_crps, colour = model_id)) +
  geom_line(linewidth = 1) +
  facet_wrap(~site_id, nrow = 2, labeller = sitenames) +
  scale_colour_viridis_d(begin = 0.2, end = 0.8) +
  labs(y = 'Median CRPS (°C)', x = 'Horizon (days ahead)', color = "") +
  theme_bw() +
  theme(legend.position = 'bottom', legend.margin = margin(t = -10),
        strip.text = element_text(size=8))
```

Compare surface in situ with all in situ

```{r}
scores_surface <- arrow::open_dataset("scores/parquet/") |>
  dplyr::collect() |>
  filter(datetime > "2021-01-01") |>
  filter(variable == "temperature") |>
  filter(horizon > 0) |>
  filter(model_id == (c("analysis_run_with_insitu", "analysis_run_with_insitu_surface",
                        "analysis_run_with_rs"))) |>
  group_by(model_id, horizon, site_id) |>
  summarize(median_crps = median(crps, na.rm = T),
            mean_crps = mean(crps, na.rm = T))

sitenames <- as_labeller(c("BARC" = "Lake Barco",
                           "bvre" = "Beaverdam Reservoir",
                           "ccre" = "Carvins Cove Reservoir",
                           "CRAM" = "Lake Crampton",
                           "fcre" = "Falling Creek Reservoir",
                           "LIRO" = "Little Rock Reservoir",
                           "PRLA" = "Prairie Lake",
                           "PRPO" = "Prairie Pothole",
                           "SUGG" = "Lake Suggs",
                           "sunp" = "Lake Sunapee"))

ggplot(data = scores_surface[!is.na(scores_surface$median_crps),], aes(x = horizon, y = median_crps, colour = model_id)) +
  geom_line(linewidth = 1) +
  facet_wrap(~site_id, nrow = 2, labeller = sitenames) +
  scale_colour_viridis_d(begin = 0.2, end = 0.8) +
  labs(y = 'Median CRPS (°C)', x = 'Horizon (days ahead)', color = "") +
  theme_bw() +
  theme(legend.position = 'bottom', legend.margin = margin(t = -10),
        strip.text = element_text(size=8))
```
